### ISSUE TITLE
URIs for periods/authorities are different in history than in dataset

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-server#133]
When getting `h.nt`, the URLs for periods and items aren't the same as the the ones in `d.jsonld`/`d.ttl` (the latter of which is returning a 500 error BTW).

Example:
```
<https://data.staging.perio.do/244q7?version=121>
    <http://www.w3.org/ns/prov#specializationOf> <https://data.staging.perio.do/244q7> ;
    <http://www.w3.org/ns/prov#wasRevisionOf> <https://data.staging.perio.do/244q7?version=120> .
```

Rather than:
```
<https:/n2t.net/ark:/99152/p0244q7?version=121>
    <http://www.w3.org/ns/prov#specializationOf> <https:/n2t.net/ark:/99152/p0244q7> ;
    <http://www.w3.org/ns/prov#wasRevisionOf> <https:/n2t.net/ark:/99152/p0244q7?version=120> .
```

**Comment by rybesh** [comment]
URLs in the history of non-canonical servers have the form `HOST/[entity id]` while on the canonical server they are `http://n2t.net/ark:/99152/p0[entity id]`.

We plan to set a new `@base` value to make this more consistent (so the dataset will be shoulder-agnostic): https://github.com/periodo/periodo-data/issues/57

The 500 error with the `d.ttl` serialization has been fixed by https://github.com/periodo/periodo-server/pull/135
