### ISSUE TITLE
Investigate slow merge

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-server#166]
Merge takes a long time right now! Need to profile it.

**Comment by ptgolden** [comment]
[stdout.txt](https://github.com/periodo/periodo-server/files/4893172/stdout.txt)

Profile of a merge attached

**Comment by ptgolden** [comment]
(using https://github.com/vpelletier/pprofile)

**Comment by ptgolden** [comment]
From some print debugging, the function that takes the longest is `void.describe_dataset`

**Comment by ptgolden** [comment]
OK, found it. Parsing the JSON-LD into RDFLib at https://github.com/periodo/periodo-server/blob/086d9917e59f0424dc36b9876a6c05e43043f4be/periodo/void.py#L20 is the the thing that takes the longest. The subsequent queries over the graph take a little bit too.

Would it be possible to generate `void.ttl` on demand, like we do with other resources, rather than saving it in the database (https://github.com/periodo/periodo-server/blob/086d9917e59f0424dc36b9876a6c05e43043f4be/periodo/patching.py#L132-L134)?

**Comment by rybesh** [comment]
Sorry, just saw these comments. OK, that makes sense, and I forgot that we rdflib to generate the void description.

I think that rather than generate the void on demand, I will see if I can generated it without using rdflib. Most of the void description doesn't change; this is just counting some things, and we don't need to parse the dataset as RDF to get those counts.

**Comment by rybesh** [comment]
I think the main reason I was doing this in RDF was to generate the [linkset descriptions](https://www.w3.org/TR/void/#describing-linksets), which, looking back on it, seems like one of those useless things we did just to demonstrate that we could. Taking these out would considerably simplify generating the void file, and I think no one would miss them.

**Comment by rybesh** [comment]
https://github.com/periodo/periodo-server/pull/167

**Comment by rybesh** [comment]
Deployed to staging and confirmed that this considerably sped up merging a patch.
