### ISSUE TITLE
History resource gives 404 with file extension

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-server#88]
`/h` is a valid URL, giving the provenance graph for the dataset. We should make `h.json`, `h.jsonld`, and `h.ttl` do the same.

`d.ttl` doesn't return an appropriate representation either, maybe we could generate & cache it as well as part of #84?

**Comment by rybesh** [comment]
The following now all resolve:

https://staging.perio.do/h.json
https://staging.perio.do/h.jsonld
https://staging.perio.do/h.ttl
https://staging.perio.do/history.json
https://staging.perio.do/history.jsonld
https://staging.perio.do/history.ttl
https://staging.perio.do/d.ttl
https://staging.perio.do/dataset.ttl

(The last two are not working right now because of invalid URIs in the dataset that break serializing to turtle—cf. https://github.com/periodo/periodo-client/issues/155. I've already fixed those in the production data.)
